from Main_Terms_In_Equations import Main_Terms_Equations
from MakeFunction_Gamma import MakeFunctions_Gamma
from Operation_with_files import Operation_with_files
from PlottingFunctions import PlottingFunctions
import os
import numpy as np

class ReadDataFilesFromSuperComputer:
    """
    This class manages the output (.txt) files with results by super-computer
    """

    def __init__(self, beta, x_values, t_value, omega_values, U, U_values,
                 NumIterations, Tolerance, Rezolution,):

        # This is the number of omega values defined by the user
        self.Rezolution = Rezolution
        # Core physical parameters
        self.beta = beta  # Inverse temperature (1/k_B*T)
        self.x_values = x_values  # Grid coordinates or spatial/momentum values
        self.t_value = t_value  # Quantum mechanical hopping parameter
        self.omegavalues = omega_values  # Matsubara or real frequency values for Green's functions
        self.U = U  # On-site electron interaction strength (current)
        self.U_values = U_values  # Array of various interaction strengths for scaling analysis

        # Iteration and numerical controls
        self.NumIteration = NumIterations
        self.Tolerance = Tolerance

        # Visualization class
        self.PF = PlottingFunctions()

        # File paths, names, and limits for data export
        self.h5py_solution_filename = 'Solutions.h5'
        self.Path_Files = 'Files'

        # Requires modification by the user. This is the name of the .txt file generated by the supercomputer.
        self.Critial_Data_File_Name = 'Data_17.txt' # Most used: Data_15.txta-U-dependemce, Data_8.txt for a-U-dependemce, Data_12.txt for  thermal a dependence , Data_17.txt for a thermal dependece of Gamma
        # Folder structure used for operations
        self.Path_Images = 'Images'

        # Initialization of helper calculation tester class
        self.D2_values_Sigma = None

    def ReadFileWithData_a(self):
        """
        This method plots results from text files generated by a supercomputer,
        with a specific focus on irreducible vertex values (Gammas) obtained from parsing the solution of the final
        nonlinear equation into the equation for the Kondo scale, which measures the distance from the superconducting scale 'a'.
        """
        filtered = []
        a_critical_beta = np.zeros((len(self.beta), len(self.U_values)))
        a_critical = np.zeros((len(self.beta), len(self.U_values)))

        roots = np.empty(a_critical_beta.shape)
        name = os.path.join(self.Path_Files, self.Critial_Data_File_Name)
        a_BCS_values = np.empty(a_critical_beta.shape)

        with open(name, "r", encoding="utf-8") as f:
            lines = f.readlines()
            for i, beta in enumerate(self.beta):
                for j, U in enumerate(self.U_values):
                    key = f'a-solution-for-U={U}-beta={beta}'
                    key_gamma = f'Gamma-solution-U={U}-beta={beta}'

                    mkf = MakeFunctions_Gamma(beta, self.x_values, self.t_value, self.omegavalues, U)
                    terms = Main_Terms_Equations(beta, self.x_values, self.t_value, self.omegavalues, U,
                                                 self.NumIteration, self.Tolerance, self.Rezolution)

                    # Compute matching baseline values derived from BCS theory
                    a_BCS_values[i, j] = terms.a_approx_BCS()

                    # Match log data strings to separate data column values
                    for line in lines:
                        if line.startswith(key):
                            value = float(line.split()[-1])
                            a_critical_beta[i, j] = value
                            a_critical[i, j] = value / (beta**2)
                        elif line.startswith(key_gamma):
                            value = float(line.split()[-1])
                            roots[i, j] = value

        # This plotting method requires further user specification regarding which data are to be plotted.

        # self.PF.Plot_Final_Dependence(
        #     self.beta,
        #     self.U_values, a_critical_beta,
        # )

        # self.PF.Plot_Final_Dependence_BCS(
        #     self.beta,
        #     self.U_values,
        #     a_critical,
        #     a_BCS_values)
        # self.PF.Plot_Final_Dependence_Transposed_BCS(
        #     self.beta,
        #     self.U_values,
        #     a_critical, a_BCS_values)

        self.PF.Plot_Final_Dependence_BCS(self.beta, self.U_values, a_critical, a_BCS_values)

    def ReadFileWithData_Gamma(self):
        """
        This method plots results from text files generated by a supercomputer,
        with a specific focus on irreducible vertex values (Gammas) obtained from parsing the solution of the final
        nonlinear equation into the equation for the vertex.
        """
        filtered = []
        a_critical_beta = np.zeros((len(self.beta), len(self.U_values)))
        Gamma_Critical = np.zeros(a_critical_beta.shape)
        roots = np.empty(a_critical_beta.shape)
        name = os.path.join(self.Path_Files, self.Critial_Data_File_Name)

        with open(name, "r", encoding="utf-8") as f:
            lines = f.readlines()
            for i, beta in enumerate(self.beta):
                for j, U in enumerate(self.U_values):
                    key_gamma_final = f'Gamma-final-for-U={U}-beta={beta}'
                    key_gamma = f'Gamma-solution-U={U}-beta={beta}'

                    mkf = MakeFunctions_Gamma(beta, self.x_values, self.t_value, self.omegavalues, U)
                    terms = Main_Terms_Equations(beta, self.x_values, self.t_value, self.omegavalues, U,
                                                 self.NumIteration, self.Tolerance, self.Rezolution)

                    # Match log data strings to separate data column values
                    for line in lines:
                        if line.startswith(key_gamma_final):
                            value = float(line.split()[-1])
                            Gamma_Critical[i, j] = value
                        elif line.startswith(key_gamma):
                            value = float(line.split()[-1])
                            roots[i, j] = value

        # This calls the plotting class and also requires further user specifications according
        # to the commented and uncommented methods to determine which data need to be plotted.

        # self.PF.Plot_Final_Dependence_BCS_Gamma(self.beta, self.U_values, a_critical_beta)
        self.PF.Plot_Final_Dependence_Transposed_BCS_Gamma(self.beta, self.U_values, Gamma_Critical)